const ShopActionTypes = {
  FETCH_COLUECTION_START: "FETCH_COLUECTION_START",
  FETCH_COLUECTION_SUCCESS: "FETCH_COLUECTION_SUCCESS",
  FETCH_COLUECTION_FAILURE: "FETCH_COLUECTION_FAILURE",
};

export default ShopActionTypes;
